def makeElements(energy=0, water=0, protein=0, fat=0, fatSat=0, carb=0, sugar=0,
                 sodium=0, chol=0, fiber=0, potassium=0, iron=0, calcium=0,
                 vitaminA=0, retinol=0, vitaminC=0, vitaminD=0, vitaminE=0,
                 vitaminESup=0, vitaminK=0, thiamin=0, riboflavin=0, niacin=0,
                 niacinSup=0, vitaminB6=0, folate=0, folateSup=0, vitaminB12=0,
                 pantothenicAcid=0, biotin=0, choline=0, chromium=0, copper=0,
                 fluoride=0, iodine=0, magnesium=0, magnesiumSup=0,
                 manganese=0, molybdenum=0, phosphorus=0, selenium=0, zinc=0,
                 boron=0, nickel=0, silicon=0, vanadium=0):
    return {'energy': energy,
            'water': water,
            'protein': protein,
            'fat': fat,
            'fatSat': fatSat,
            'carb': carb,
            'sugar': sugar,
            'sodium': sodium,
            'chol': chol,
            'fiber': fiber,
            'potassium': potassium,
            'iron': iron,
            'calcium': calcium,
            'vitaminA': vitaminA,
            'retinol': retinol,
            'vitaminC': vitaminC,
            'vitaminD': vitaminD,
            'vitaminE': vitaminE,
            'vitaminESup': vitaminESup,
            'vitaminK': vitaminK,
            'thiamin': thiamin,
            'riboflavin': riboflavin,
            'niacin': niacin,
            'niacinSup': niacinSup,
            'vitaminB6': vitaminB6,
            'folate': folate,
            'folateSup': folateSup,
            'vitaminB12': vitaminB12,
            'pantothenicAcid': pantothenicAcid,
            'biotin': biotin,
            'choline': choline,
            'chromium': chromium,
            'copper': copper,
            'fluoride': fluoride,
            'iodine': iodine,
            'magnesium': magnesium,
            'magnesiumSup': magnesiumSup,
            'manganese': manganese,
            'molybdenum': molybdenum,
            'phosphorus': phosphorus,
            'selenium': selenium,
            'zinc': zinc,
            'boron': boron,
            'nickel': nickel,
            'silicon': silicon,
            'vanadium': vanadium
    }

def makeElementsUnits():
    return makeElements(
            energy = 'kcal',
            water = 'g',
            protein = 'g',
            fat = 'g',
            fatSat = 'g',
            carb = 'g',
            sugar = 'g',
            sodium = 'mg',
            chol = 'mg',
            fiber = 'g',
            potassium = 'mg',
            iron = 'mg',
            calcium = 'mg',
            vitaminA = 'RAE',
            retinol = 'mcg',
            vitaminC = 'mg',
            vitaminD = 'mcg',
            vitaminE = 'mg',
            vitaminESup = 'mg',
            vitaminK = 'mcg',
            thiamin = 'mcg',
            riboflavin = 'mcg',
            niacin = 'mg',
            niacinSup = 'mg',
            vitaminB6 = 'mcg',
            folate = 'DFE',
            folateSup = 'DFE',
            vitaminB12 = 'ng',
            pantothenicAcid = 'mcg',
            biotin = 'mcg',
            choline = 'mg',
            chromium = 'mcg',
            copper = 'mcg',
            fluoride = 'mcg',
            iodine = 'mcg',
            magnesium = 'mg',
            magnesiumSup = 'mg',
            manganese = 'mcg',
            molybdenum = 'mcg',
            phosphorus = 'mg',
            selenium = 'mcg',
            zinc = 'mg',
            boron = 'mg',
            nickel = 'mcg',
            silicon = 'mg',
            vanadium = 'mcg'
    )
